### ISSUE TITLE
"Expect completed on" dates set in Dates report don't appear to create calendar events

### ISSUE THREAD

**Issue by QPEIFFE** [moodleou/moodle-report_editdates#60] opened 2024-01-07 22:03 UTC
Hi there!  Running [Moodle 4.1.6+ (Build: 20231027)].

We're running into an issue where, when editing the "Expect completed on" date for Quiz activities, calendar events for that date aren't being created for the participants in either the Dashboard calendar or the Calendar block in the course.  When I step into the Quiz settings page, then save without making any changes, the calendar event is created.

Is there some kind of action taken by the settings save that creates the event that isn't firing in the Dates report?  It looks like this has been reported before: https://github.com/moodleou/moodle-report_editdates/issues/19

Thank you!

**Comment by QPEIFFE** [comment] 2024-01-09 20:50
Following up—has anyone taken a look at this?  Thank you kindly!

**Comment by timhunt** [comment] 2024-01-18 09:47
Right, so this is a duplicate of #19, and what is said there is still the latest position.

**Closed by timhunt** 2024-01-18 09:47 UTC
